const $=id=>document.getElementById(id);
const backend=window.location.origin.replace(/\/$/,'');
let token=localStorage.getItem('aether_token')||''; let mode='login'; let conversation=null;
const oauthToken=new URLSearchParams(location.search).get('oauth_token'); if(oauthToken){token=oauthToken;localStorage.setItem('aether_token',token);history.replaceState({},'',location.pathname);}
const FEATURES=[['🧠','ManagerAI','Default orchestrator: understands the task, delegates to specialists, and combines their reports.'],['💡','ReasonAI','Breaks down difficult problems, checks assumptions, compares approaches, and reasons through decisions.'],['💻','CodeAI','Builds, debugs, explains, and improves software, with connected developer tools when configured.'],['🔎','ResearchAI','Researches current information, news, and public websites and synthesizes the evidence.'],['🎨','Image generation','Creates images from prompts when the image-generation service is configured.'],['🗂️','Saved history','Account chats can be saved; guest chats remain temporary.']];
function setStatus(m,ok=false){const e=$('authNote');if(e){e.textContent=m;e.dataset.ok=ok?'1':'0';}}
function switchMode(n){mode=n;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===n));$('authBtn').textContent=n==='login'?'Log in to Aether':'Create my Aether account';$('authTitle').textContent=n==='login'?'Welcome back':'Create your Aether account';$('authSubtitle').textContent=n==='login'?'Your AI team is ready.':'Create an account to keep your conversations and history.';setStatus('');}
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(backend+path,{...opt,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||`Request failed (${r.status})`);return d;}
function openApp(){localStorage.setItem('aether_token',token);$('auth').classList.add('hidden');$('app').classList.remove('hidden');bootApp();}
async function authSubmit(){const email=$('email').value.trim(),password=$('password').value;if(!email||!password)return setStatus('Enter your email and password first.');if(password.length<6)return setStatus('Use a password with at least 6 characters.');const b=$('authBtn');b.disabled=true;setStatus(mode==='login'?'Signing you in…':'Creating your account…');try{const d=await api(mode==='login'?'/api/auth/login':'/api/auth/register',{method:'POST',body:JSON.stringify({email,password})});token=d.token;setStatus('Success. Opening Aether…',true);openApp();}catch(e){setStatus(e.message)}finally{b.disabled=false}}
async function guestLogin(){const b=$('guestBtn');b.disabled=true;setStatus('Starting a temporary guest session…');try{const d=await api('/api/auth/guest',{method:'POST',body:JSON.stringify({name:'Guest'})});token=d.token;openApp()}catch(e){setStatus(e.message)}finally{b.disabled=false}}
async function oauth(p){try{const d=await api('/api/auth/providers');if(!d[p])return setStatus(`${p[0].toUpperCase()+p.slice(1)} sign-in is not configured on the Aether backend yet.`);location.href=backend+`/api/auth/oauth/${p}`}catch(e){setStatus(e.message)}}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML;}
function addMessage(role,text,image){const box=$('messages');if(box.querySelector('.welcome'))box.innerHTML='';const el=document.createElement('div');el.className=`message ${role}`;let html=`<div class="bubble">${escapeHtml(text)}`;if(image)html+=`<img class="genimg" src="${image}" alt="Generated image">`;html+='</div>';el.innerHTML=html;box.appendChild(el);box.parentElement.scrollTop=box.parentElement.scrollHeight;}
async function sendMessage(){const input=$('input'),text=input.value.trim();if(!text)return;const agent=$('agent').value,locationText=$('location').value.trim();addMessage('user',text);input.value='';const btn=document.querySelector('.send');btn.disabled=true;try{const d=await api('/api/chat',{method:'POST',body:JSON.stringify({message:text,agent,conversation_id:conversation,location:locationText||null})});conversation=d.conversation_id;addMessage('assistant',d.answer,d.image_data||null);if($('agentName')){$('agentName').textContent=d.agent;$('agentName').nextElementSibling.textContent=agent==='manager'?'Team manager / orchestrator':`Aether specialist · ${d.agent}`}}catch(e){addMessage('assistant',`Aether error: ${e.message}`)}finally{btn.disabled=false;input.focus()}}
async function loadHistory(){try{const d=await api('/api/history');const box=$('history');if(!box)return;box.innerHTML='';if(!d.history?.length){box.innerHTML='<small class="muted">No saved chats yet.</small>';return;}d.history.slice(0,20).forEach(x=>{const b=document.createElement('button');b.className='history-item';b.textContent=x.title||'Untitled chat';b.onclick=()=>openHistory(x.id);box.appendChild(b);});}catch(e){}}
async function openHistory(id){try{const d=await api('/api/history/'+encodeURIComponent(id));conversation=id;$('messages').innerHTML='';(d.messages||[]).forEach(m=>addMessage(m.role==='user'?'user':'assistant',m.content));}catch(e){addMessage('assistant','Could not load that saved chat: '+e.message)}}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));$('authBtn')?.addEventListener('click',authSubmit);$('guestBtn')?.addEventListener('click',guestLogin);$('googleBtn')?.addEventListener('click',()=>oauth('google'));$('githubBtn')?.addEventListener('click',()=>oauth('github'));$('password')?.addEventListener('keydown',e=>{if(e.key==='Enter')authSubmit()});$('composer')?.addEventListener('submit',e=>{e.preventDefault();sendMessage()});$('newChat')?.addEventListener('click',()=>{conversation=null;$('messages').innerHTML='<div class="welcome"><div class="orb">✦</div><h2>New Aether chat.</h2><p>Ask ManagerAI anything.</p></div>';$('input').focus()});$('logout')?.addEventListener('click',()=>{localStorage.removeItem('aether_token');location.reload()});document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{$('input').value=b.dataset.q;$('input').focus()});$('agent')?.addEventListener('change',e=>{const n=e.target.options[e.target.selectedIndex].text.split(' — ')[0];$('agentName').textContent=n;$('agentName').nextElementSibling.textContent=n==='ManagerAI'?'Team manager / orchestrator':`Aether specialist · ${n}`});}
async function boot(){if(!token)return;try{const c=await api('/api/config');if($('modelStatus'))$('modelStatus').textContent=c.model_connected?`AI online · ${c.model||'model connected'}`:'AI provider not configured';const h=await api('/api/history');if($('historyState'))$('historyState').textContent=h.saved?`${h.history.length} saved`:'Guest';if(h.saved)loadHistory();}catch(e){localStorage.removeItem('aether_token');token='';location.reload();}}
bind();boot();